### YamlMime:Lifecycle
metadata:
  title: Microsoft Intelligent Application Gateway 2007
  description: Microsoft Intelligent Application Gateway 2007 mengikuti kebijakan siklus hidup tetap.
  ms.date: 07/28/2020
  ms.openlocfilehash: 6e5cc4784788d27433b7525f6a900cbc1e9f0713
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: id-ID
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "823607"
name: Microsoft Intelligent Application Gateway 2007
summary: >
  Microsoft Intelligent Application Gateway 2007 mengikuti kebijakan siklus hidup [tetap](/lifecycle/policies/fixed) .



  > [!IMPORTANT]

  > Dukungan untuk produk ini telah berakhir. Lihat panduan migrasi di bawah.
products:
- microsoft-servers
policyType: fixed
supportDates:
  start: 06/01/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Service Pack 2
  startDate: 11/27/2008
  endDate: 07/11/2017
- version: Service Pack 1
  startDate: 09/03/2007
  endDate: 01/12/2010
- version: Original Release
  startDate: 06/01/2007
  endDate: 10/14/2008
content: "\n## <a name=\"links\"></a>Link \n* [Peta strategi Microsoft Intelligent Application Gateway 2007](/archive/blogs/testtesttestbug/important-changes-to-the-forefront-product-line)\n* [Kebijakan Paket Layanan](/lifecycle/policies/fixed#service-packs)"
