### YamlMime:Lifecycle
metadata:
  title: Virtualisasi aplikasi Microsoft 5,0
  description: 5,0 virtualisasi aplikasi Microsoft mengikuti kebijakan siklus hidup tetap.
  ms.date: 07/28/2020
  ms.openlocfilehash: 537410789f17e2ca2d9308c1814f22f823288b32
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: id-ID
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "856372"
name: Virtualisasi aplikasi Microsoft 5,0
summary: >+
  Virtualisasi aplikasi Microsoft 5,0 mengikuti kebijakan siklus hidup [tetap](/lifecycle/policies/fixed) .


  Hal ini berlaku untuk edisi berikut ini: untuk layanan desktop jarak jauh, untuk layanan terminal, untuk Windows Desktop

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2012
  end: 01/09/2018
  extendedEnd: 01/10/2023
releases:
- version: Service Pack 3
  startDate: 12/08/2014
  endDate: 01/10/2023
- version: Service Pack 2
  startDate: 12/02/2013
  endDate: 01/12/2016
- version: Service Pack 1
  startDate: 04/10/2013
  endDate: 01/13/2015
- version: Original Release
  startDate: 11/01/2012
  endDate: 07/08/2014
content: "\n## <a name=\"links\"></a>Link \n* [Informasi produk](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n* [Kebijakan Paket Layanan](/lifecycle/policies/fixed#service-packs)\n\n\n## <a name=\"editions\"></a>Edisi \n* untuk layanan desktop jarak jauh\n* untuk layanan Terminal\n* untuk Windows Desktop"
