### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security mengikuti Kebijakan Siklus Hidup Tetap.
  ms.date: 08/28/2020
  ms.openlocfilehash: 335ae81ffa4b7cb64352b19e7330765a4cac6c68
  ms.sourcegitcommit: 570c824dbe19150d37398333df7d2c416a51eac9
  ms.translationtype: HT
  ms.contentlocale: id-ID
  ms.lasthandoff: 08/28/2020
  ms.locfileid: "924259"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security mengikuti Kebijakan Siklus Hidup [Tetap](/lifecycle/policies/fixed).


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Tautan \n* [System Center Endpoint Protection (Perlindungan Endpoint Pusat Sistem)](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront Client Security telah dihentikan per tanggal 14 Juli 2015. Pembaruan definisi Antimalware dan Antispyware tidak akan lagi tersedia setelah akhir masa dukungan untuk versi produknya. Mohon evaluasi System Center Endpoint Protection sebagai penggantinya."
