### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 untuk Windows Desktop
  description: Microsoft Application Virtualization Hosting 5.1 untuk Windows Desktop mengikuti Kebijakan Siklus Hidup Tetap.
  ms.date: 09/10/2020
  keywords: for Windows Desktops
name: Microsoft Application Virtualization Hosting 5.1 untuk Windows Desktop
summary: |+
  Microsoft Application Virtualization Hosting 5.1 untuk Windows Desktop mengikuti Kebijakan Siklus Hidup [Tetap](/lifecycle/policies/fixed).

  Hal ini berlaku untuk edisi berikut: untuk Windows Desktops

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Original Release
    startDate: 11/01/2015
    endDate: 04/14/2026
content: |

  ## <a name="links"></a>Tautan 
  * [Informasi produk](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)


  ## <a name="editions"></a>Edisi 
  * Untuk Windows Desktops