### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R2
  description: Microsoft System Center Configuration Manager 2007 R2 mengikuti kebijakan siklus hidup tetap.
  ms.date: 07/28/2020
  ms.openlocfilehash: 0da71b9a2886e1a7012339ebef9a5fbe64f8811e
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: id-ID
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "823466"
name: Microsoft System Center Configuration Manager 2007 R2
summary: >
  Microsoft System Center Configuration Manager 2007 R2 mengikuti kebijakan siklus hidup [tetap](/lifecycle/policies/fixed) .



  > [!IMPORTANT]

  > Dukungan untuk produk ini telah berakhir. Lihat panduan migrasi di bawah.
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2008
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 11/29/2008
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Link \n* [Panduan migrasi](/mem/configmgr/core/migration/planning-for-migration)\n* [Panduan migrasi tambahan](/mem/configmgr/core/migration/migrate-data-between-hierarchies)"
