### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security mengikuti Kebijakan Siklus Hidup Tetap.
  ms.date: 08/28/2020
  ms.openlocfilehash: d85aea21441458397839241e74939536051397d4
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: id-ID
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4113412"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security mengikuti Kebijakan Siklus Hidup [Tetap](/lifecycle/policies/fixed).


products:
- msc
policyType: fixed
supportDates:
  start: 2007-08-02T00:00:00.000-08:00
  extendedEnd: 2015-07-14T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2007-08-02T00:00:00.000-08:00
  endDate: 2015-07-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Tautan \n* [System Center Endpoint Protection (Perlindungan Endpoint Pusat Sistem)](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront Client Security telah dihentikan per tanggal 14 Juli 2015. Pembaruan definisi Antimalware dan Antispyware tidak akan lagi tersedia setelah akhir masa dukungan untuk versi produknya. Mohon evaluasi System Center Endpoint Protection sebagai penggantinya."
