### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 mengikuti Kebijakan Siklus Hidup Tetap.
  ms.date: 07/28/2020
name: Microsoft System Center Configuration Manager 2007 R3
summary: |
  Microsoft System Center Configuration Manager 2007 R3 mengikuti Kebijakan Siklus Hidup [Tetap](/lifecycle/policies/fixed).


  > [!IMPORTANT]
  > Dukungan untuk produk ini telah berakhir. Lihat panduan migrasi di bawah.
products:
  - msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Original Release
    startDate: 12/19/2010
    endDate: 07/09/2019
content: |+

  ## <a name="links"></a>Tautan 
  * [Panduan migrasi](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [Panduan migrasi tambahan](/mem/configmgr/core/migration/planning-for-migration)