### YamlMime:Lifecycle
metadata:
  title: Microsoft aplikasi virtualisasi hosting 5,1 untuk Windows Desktop
  description: Microsoft aplikasi virtualisasi hosting 5,1 untuk Windows Desktop mengikuti kebijakan siklus hidup tetap.
  ms.date: 07/28/2020
  ms.openlocfilehash: c6fc257da84e3276165d0ab97a736120c1424172
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: id-ID
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "856552"
name: Microsoft aplikasi virtualisasi hosting 5,1 untuk Windows Desktop
summary: >+
  Microsoft aplikasi virtualisasi hosting 5,1 untuk Windows Desktop mengikuti kebijakan siklus hidup [tetap](/lifecycle/policies/fixed) .


  Hal ini berlaku untuk edisi berikut ini: untuk Windows Desktop

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Link \n* [Informasi produk](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Edisi \n* untuk Windows Desktop"
