### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007
  description: Microsoft System Center Configuration Manager 2007 mengikuti Kebijakan Siklus Hidup Tetap.
  ms.date: 07/28/2020
name: Microsoft System Center Configuration Manager 2007
summary: |
  Microsoft System Center Configuration Manager 2007 mengikuti Kebijakan Siklus Hidup [Tetap](/lifecycle/policies/fixed).


  > [!IMPORTANT]
  > Dukungan untuk produk ini telah berakhir. Lihat panduan migrasi di bawah.
products:
  - msc
policyType: fixed
supportDates:
  start: 11/29/2007
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Service Pack 2
    startDate: 10/22/2009
    endDate: 07/09/2019
  - version: Service Pack 1
    startDate: 05/21/2008
    endDate: 01/11/2011
  - version: Original Release
    startDate: 11/29/2007
    endDate: 07/14/2009
content: |+

  ## <a name="links"></a>Tautan 
  * [Panduan migrasi](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [Informasi produk](/mem/configmgr/core/understand/introduction)
  * [Kebijakan paket layanan](/lifecycle/policies/fixed#service-packs)