### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager (LTSB - versi 1606)
  description: Microsoft System Center Configuration Manager (LTSB - versi 1606) mengikuti Kebijakan Siklus Hidup Tetap.
  ms.date: 08/20/2020
  ms.openlocfilehash: c918fa35a50ffac8ee9d31cb0b704aac444cefe1
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: id-ID
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4106197"
name: Microsoft System Center Configuration Manager (LTSB - versi 1606)
summary: >+
  Microsoft System Center Configuration Manager (LTSB - versi 1606) mengikuti Kebijakan Siklus Hidup [Tetap](/lifecycle/policies/fixed).


products:
- m365
policyType: fixed
supportDates:
  start: 2016-10-12T00:00:00.000-08:00
  end: 2021-10-12T22:59:59.999-08:00
  extendedEnd: 2027-01-12T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2016-10-12T00:00:00.000-08:00
  endDate: 2027-01-12T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Tautan \n* [Informasi servis dan dukungan](/sccm/core/understand/learn-more-editions)"
