### YamlMime:Lifecycle
metadata:
  title: Virtualisasi Aplikasi SoftGrid
  description: Virtualisasi Aplikasi SoftGrid mengikuti Kebijakan Siklus Hidup Tetap.
  ms.date: 09/10/2020
  keywords: 4.1 for Desktops,4.2 for Desktops,for Terminal Services 4.1
  ms.openlocfilehash: 5009a44f0d0ab2b180f62474de8f4d4bb01e3e62
  ms.sourcegitcommit: c0c65f657b1da8e588fda5bedd3572fb2e3168bc
  ms.translationtype: HT
  ms.contentlocale: id-ID
  ms.lasthandoff: 09/10/2020
  ms.locfileid: "1001023"
name: Virtualisasi Aplikasi SoftGrid
summary: >
  Virtualisasi Aplikasi SoftGrid mengikuti Kebijakan Siklus Hidup [Tetap](/lifecycle/policies/fixed).


  Berlaku untuk edisi berikut ini: 4.1 untuk Desktop, 4.2 untuk Desktop, untuk Layanan Terminal 4.1


  > [!IMPORTANT]

  > Dukungan telah berakhir. Lihat panduan migrasi di bawah.
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>Tautan \n* [Panduan migrasi](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Edisi \n* 4.1 untuk Desktop\n* 4.2 untuk Desktop\n* untuk Layanan Terminal 4.1"
