### YamlMime:Lifecycle
metadata:
  title: Virtualisasi Aplikasi SoftGrid
  description: Virtualisasi Aplikasi SoftGrid mengikuti Kebijakan Siklus Hidup Tetap.
  ms.date: 09/10/2020
  keywords: '4.1 for Desktops,4.2 for Desktops,for Terminal Services 4.1'
name: Virtualisasi Aplikasi SoftGrid
summary: |
  Virtualisasi Aplikasi SoftGrid mengikuti Kebijakan Siklus Hidup [Tetap](/lifecycle/policies/fixed).

  Berlaku untuk edisi berikut ini: 4.1 untuk Desktop, 4.2 untuk Desktop, untuk Layanan Terminal 4.1

  > [!IMPORTANT]
  > Dukungan telah berakhir. Lihat panduan migrasi di bawah.
products:
  - windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
  - version: Original Release
    startDate: 05/25/2007
    endDate: 07/11/2017
content: |

  ## <a name="links"></a>Tautan 
  * [Panduan migrasi](https://technet.microsoft.com/en-us/windows/bb899442)


  ## <a name="editions"></a>Edisi 
  * 4.1 untuk Desktop
  * 4.2 untuk Desktop
  * untuk Layanan Terminal 4.1