### YamlMime:Lifecycle
metadata:
  title: Aplikasi SoftGrid virtualisasi
  description: Virtualisasi aplikasi SoftGrid mengikuti kebijakan siklus hidup tetap.
  ms.date: 07/28/2020
  ms.openlocfilehash: 17b8078138b718a634c2561ac4b1e73f3966ce24
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: id-ID
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "822886"
name: Aplikasi SoftGrid virtualisasi
summary: >
  Virtualisasi aplikasi SoftGrid mengikuti kebijakan siklus hidup [tetap](/lifecycle/policies/fixed) .


  Hal ini berlaku untuk edisi berikut ini: 4,1 untuk desktop, 4,2 untuk desktop, Layanan Terminal 4,1


  > [!IMPORTANT]

  > Dukungan telah berakhir. Lihat panduan migrasi di bawah.
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>Link \n* [Panduan migrasi](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Edisi \n* 4,1 untuk desktop\n* 4,2 untuk desktop\n* untuk layanan Terminal 4,1"
